First android prototype with our model. Issue #26.
cvlab-ai/polish_banknotes pull request #36
Opened 2022-11-28 14:10 UTC by jankejc

- Branch contains whole app prototype with our model.
- It also contains the way to add metadata.
- Branch does not contain `build` folder because it was too large.
- Branch closes issue #26.

2022-11-28 14:41 UTC, qaziok submitted a review, later dismissed
Gites że jest - niech jeszcze @kjedrasz2137 klepnie czy wszystko się zgadza

2022-11-28 15:22 UTC, kjedrasz2137 requested changes
Please read my comments and make the necessary corrections.

2022-11-28 15:22 UTC, kjedrasz2137 commented on Android/adding_metadata/readme.txt
> +3. In file we are using mean = 0 and std = 1. That's because our model is already normalized, so we need to add metadata only.
Our model has a normalization layer inside, i.e. `layers.Rescaling()`, that is why we can set mean = 0 and std = 1 in the metadata file.

2022-11-28 15:22 UTC, kjedrasz2137 commented on Android/adding_metadata/readme.txt
> +python ./metadata_writer_for_image_classifier.py --model_file=./model_1_0.tflite --label_file=./labels.txt --export_directory=./model_with_metadata/python ./metadata_writer_for_image_classifier.py --
If we use folder `model_with_medata`, maybe we can also use a similar folder called `model_without_metada`?

2022-11-28 15:22 UTC, kjedrasz2137 commented on Android/adding_metadata/metadata_writer_for_image_classifier.py
> +            image_max=1.0,
`image_min` should be 0 and `image_max` should be 255

2022-11-28 15:22 UTC, kjedrasz2137 commented on Android/adding_metadata/metadata_writer_for_image_classifier.py
> +            mean=[0],
Please set mean = [0.0], std = [1.0]

2022-11-28 15:22 UTC, kjedrasz2137 commented on Android/adding_metadata/labels.txt
> +none
Should be `None`

2022-11-28 15:22 UTC, kjedrasz2137 commented on Android/PolishBanknotesApp/app/src/main/java/org/tensorflow/lite/examples/imageclassification/fragments/CameraFragment.kt
> +            if (imageClassifierHelper.maxResults < 3) {
Compare `imageClassifierHelper.maxResults` with number of classes, which in our case is 7.

2022-11-29 09:12 UTC, jankejc reviewed
All the requested changes have been applied.

2022-11-29 11:19 UTC, kjedrasz2137 approved these changes

2022-11-29 11:19 UTC, kjedrasz2137 commented
Looks good

2022-11-29 11:24 UTC, merged